In [5]:
import numpy as np 
from sklearn import datasets
from sklearn.model_selection import train_test_split
#report用于计算f1等指标的值
#confusion_matrix指混淆矩阵，行相加为真实值，列相加为分类值
from sklearn.metrics import classification_report,confusion_matrix
#operaator里封装了一些数学函数供使用
import operator
import random

In [2]:
a = np.array([[1,2],
             [1,2],
             [1,2]])
#按列求和 这个’列’可以理解为一列，再垂直这个列的方向逐渐求和
#拍扁
a.sum(axis = 1)

array([3, 3, 3])

In [3]:
# 把数组沿各个方向复制
# 纵向 3 次， 横向 1 次
np.tile(a,(3,1))

array([[1, 2],
       [1, 2],
       [1, 2],
       [1, 2],
       [1, 2],
       [1, 2],
       [1, 2],
       [1, 2],
       [1, 2]])

In [4]:
np.tile(a, (2,2))

array([[1, 2, 1, 2],
       [1, 2, 1, 2],
       [1, 2, 1, 2],
       [1, 2, 1, 2],
       [1, 2, 1, 2],
       [1, 2, 1, 2]])

In [21]:
a = np.array([8,5,3,6,7])
print(np.argmax(a))
print(np.argmin(a))

# 对arr中的值进行排序后，对应值的下标
b = np.argsort(a)
b

0
2


array([2, 1, 3, 4, 0])

In [28]:
print("index\tvalue")
for i in range(len(a)):
    print(b[i],':\t',a[b[i]])

index	value
2 :	 3
1 :	 5
3 :	 6
4 :	 7
0 :	 8


In [6]:
def knn(x_test,x_data,y_data,k):  #x_test 是单个样本!
    # 计算样本数量
    # 准确来讲计算的是行数
    x_data_size = x_data.shape[0]
    # 复制x_test,即 将单个样本复制数据样本个数次
    np.tile(x_test,(x_data_size,1))
    # 计算x_test与每一个样本的差值
    diffMat = np.tile(x_test,(x_data_size,1)) - x_data
    # 计算差值的平方
    sqDiffMat = diffMat**2
    # 求和  
    sqDistances = sqDiffMat.sum(axis=1)
    # 开方
    distances = sqDistances**0.5
    # 从大到小排序
    sortedDistances = distances.argsort()
    classCount = {}
    for i in range(k):
        votelabel = y_data[sortedDistances[i]]
        # 统计标签数量
        # dict.get(value, default)
        classCount[votelabel] = classCount.get(votelabel,0)+1
    # 根据operator.itemgetter(1)-第一个值对classCount排序，然后再取倒序
    sortedClassCount = sorted(classCount.items(),key=operator.itemgetter(1),reverse=True)
    # 获取数量最多的标签
    return sortedClassCount[0][0]

In [7]:
#载入数据
iris = datasets.load_iris()
#x_train,x_test,y_train,y_test = train_test_split(iris.data,iris.target,test_size=0.2)
#上面意思是分割数据0.2为测试数据，0.8为训练数据


#以下方法均是自主打乱数据的方法
#打乱数据
data_size = iris.data.shape[0]
#生成一个列表List
index = [i for i in range(data_size)]
#把列表传进去之后shuffle函数自动帮我们打乱它
random.shuffle(index)
iris.data = iris.data[index]
iris.target = iris.target[index]

#切分数据集
test_size = 40
x_train = iris.data[test_size:]
x_test = iris.data[:test_size]
y_train = iris.target[test_size:]
y_test = iris.target[:test_size]

#空表
predictions = ([])

for i in range(x_test.shape[0]):
    # x_test[i] 是一个样本,即对单个样本进行分类
    predictions.append(knn(x_test[i],x_train,y_train,5))

print(classification_report(y_test,predictions))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        16
           1       1.00      0.92      0.96        13
           2       0.92      1.00      0.96        11

    accuracy                           0.97        40
   macro avg       0.97      0.97      0.97        40
weighted avg       0.98      0.97      0.98        40



In [8]:
print(confusion_matrix(y_test,predictions))
#可以看出第二行有两个数据分类错了，knn算法的预测较为准确
#这里多阐述一下
#正确的预测结果都在对角线上，所以从混淆矩阵中可以很方便直观的看出哪里有错误，因为他们呈现在对角线外面。

[[16  0  0]
 [ 0 12  1]
 [ 0  0 11]]


In [9]:
predictions.count(2)

12

In [10]:
type(predictions)


list

In [11]:
a = list(y_test)

In [12]:
count = 0
cont_list = [0,0,0]
for i in range(len(y_test)):
    if(y_test[i]==predictions[i]):
        if(y_test[i]==0):
            cont_list[0]+=1
        elif(y_test[i]==1):
            cont_list[1]+=1
        else:
            cont_list[2]+=1
        count+=1
    
        
accuryce = count/len(y_test) 
print("Toatal_accuryce = %f\nClass0_accuracy = %f\nClass1_accuracy = %f\nClass2_accuracy = %f\n"% (accuryce,
      cont_list[0]/a.count(0),cont_list[1]/a.count(1),cont_list[2]/a.count(2),)
     )

Toatal_accuryce = 0.975000
Class0_accuracy = 1.000000
Class1_accuracy = 0.923077
Class2_accuracy = 1.000000

